import type { Metadata } from "next";

import { Inter, Roboto } from "next/font/google";

import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";

import { RootWrapper } from "@/app/layouts/RootWrapper";
import ReactQueryProviders from "@/app/providers/ReactQuery";

import "../styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="ko" className={roboto.variable}>
      <body className={inter.className} suppressContentEditableWarning>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <ReactQueryProviders>
            <RootWrapper>{children}</RootWrapper>
          </ReactQueryProviders>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
